# TensorFlow Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [3]:
# Creating tensors with t.constant()

scalar = tf.constant([10, 10])
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [4]:
# Check the no. of dimensions of a Tensor (ndim : No. of Dimensions)

scalar.ndim, matrix.ndim

(1, 2)

* **Scalar :** Single Number
* **Vector :** a number with a direction 
* **Matrix :** a 2-dimensional array of numbers
* **Tensor :** an n-dimensional array of numbers

 ## Creating tensors with  `tf.varialble`

In [5]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [6]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [7]:
# Changing one of elements in the changeable tensor

changeable_tensor[0].assign(99)

changeable_tensor
# We can't do the same thing with the tf.constant

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([99,  7], dtype=int32)>

**Note :** If in doubt which one to use, use `tf.constant` and change it later if needed

## Creating Random tensors

Random tensors are tensors of some arbitary size which contains random numbers.

In [8]:
random1 = tf.random.Generator.from_seed(42) 
random1 = random1.uniform(shape = [3, 2])
random2 = tf.random.Generator.from_seed(42) 
random2 = random2.normal(shape = [3, 2])
random1, random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

**Shuffling the order of elements in a Tensor**

In [9]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [1, 2]])

not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 1,  2]], dtype=int32)>, 2)

In [10]:
shuffled = tf.random.shuffle(not_shuffled) 

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 1,  2],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [11]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

## Other ways to create Tensors

In [12]:
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

#### Turning NumPy array into TensorFlow tensors

NumPy Arrays v/s TensorFlow Tensors 
Tensors can be run one GPU

In [14]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [15]:
numpy_tensor = tf.constant(numpy_A, shape=[2, 2, 6])
numpy_tensor

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]], dtype=int32)>

## Getting Information from Tensors

* Shape
* Rank
* Axis/Dimension
* Size

In [16]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [17]:
# Get various attributes of tensor
print("Data-type of every element :", rank_4_tensor.dtype)
print("Number of dimensions (rank) :", rank_4_tensor.ndim)
print("Shape of tensor :", rank_4_tensor.shape)
print("Elements along axis 0 of tensor :", rank_4_tensor.shape[0])
print("Elements along last axis of tensor :", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5) :", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Data-type of every element : <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Elements along axis 0 of tensor : 2
Elements along last axis of tensor : 5
Total number of elements (2*3*4*5) : 120


## Indexing our Tensors

Tensors can be index just like python Lists.

In [18]:
# Get The first two elements in each dimenions of our rank_4_tensor

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [19]:
# Get first elements from each dimension except the final one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [20]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [21]:
# Adding extra dimension to our tensor 2dim->3dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## Manipulating the Tensors 

**Basic Operations**

In [22]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [23]:
# We can use TF Built-in functions

tf.multiply(tensor, 10), tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

#### Speed test : Python Operations v/s TF Operations

In [24]:
tensor_test = tf.constant([[0, 1],
                           [1, 0]])
import timeit

In [25]:
def speed_test(tensor_test, value):
  start = timeit.default_timer()
  for i in range(value):
    tensor_test+=1
  stop = timeit.default_timer()
  v1=stop-start
  print('Python Op Time: ', stop - start)  

  start = timeit.default_timer()
  for i in range(value):
    tensor_test = tf.add(tensor, 1)
  stop = timeit.default_timer()
  v2=stop-start
  print('TF Op Time: ', stop - start)  
  print("TF is "+str(v1/v2)+" times faster than Python")

In [26]:
# speed_test(tensor_test, 1000000)

# OUTPUT:
# Python Op Time:  29.134950077000212
# TF Op Time:  8.4106564169997
# TF is 3.4640518685452864 times faster than Python

## Aggregating Tensors 

Condensing them from Multiple Values to a Smaller Amount of Values.

In [39]:
tensor = tf.constant([-1, -10])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -1, -10], dtype=int32)>

In [40]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

In [44]:
tf.reduce_min(tensor), tf.reduce_max(tensor), tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=-10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-11>)

In [53]:
import tensorflow_probability as tfp

tfp.stats.variance(tensor), tf.sqrt(tf.cast(tfp.stats.variance(tensor), dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int32, numpy=20>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.472136>)

### Positional Maximum and Minimum

In [56]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [59]:
tf.argmax(tensor), tf.reduce_max(tensor), tensor[tf.argmax(tensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

### Squeezing the Tensors : Removing all single dimensions

In [64]:
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [66]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
       0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
       0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
       0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
       0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
       0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
       0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
       0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
       0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
       0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
      dtype=float32)>

## One Hot Encoding the Tensors 

In [69]:
# Create a list of indices
some_list = [0, 1, 2, 3, 4]
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [70]:
tf.one_hot(some_list, depth=5, on_value='Y', off_value='N')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N', b'N'],
       [b'N', b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'N', b'Y']], dtype=object)>