<a href="https://colab.research.google.com/github/gauravreddy08/deep-learning-tensorflow/blob/main/notebooks/00_basics-tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Basics of Tensorsflow**

In [1]:
import tensorflow as tf
print(tf.__version__)

2.4.1


## **Understanding Tensors**
In mathematics, a tensor is an algebraic object that describes a relationship between sets of algebraic objects related to a vector space. Objects that tensors may map between include vectors and scalars, and even other tensors. 

### **Creating tensors with `tf.constant()`**


In [2]:
scalar = tf.constant([10, 10])
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

### **Check the no. of dimensions of a Tensor : `ndim`**

In [3]:
scalar.ndim, matrix.ndim

(1, 2)

* **Scalar :** Single Number
* **Vector :** a number with a direction 
* **Matrix :** a 2-dimensional array of numbers
* **Tensor :** an n-dimensional array of numbers

 ## **Creating tensors with  `tf.varialble`**

In [4]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [5]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

### **Understanding Variable Tensors**

In [6]:
# Changing one of elements in the changeable tensor

changeable_tensor[0].assign(99)

changeable_tensor
# We can't do the same thing with the tf.constant

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([99,  7], dtype=int32)>

**Note :** If in doubt which one to use, use `tf.constant` and change it later if needed

## **Creating Random tensors**

Random tensors are tensors of some arbitary size which contains random numbers.

In [8]:
random1 = tf.random.Generator.from_seed(42) 
random1 = random1.uniform(shape = [3, 2])
random2 = tf.random.Generator.from_seed(42) 
random2 = random2.normal(shape = [3, 2])
random1, random2, random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.7493447 , 0.73561966],
        [0.45230794, 0.49039817],
        [0.1889317 , 0.52027524]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### **Shuffling the order of elements in a Tensor**

In [9]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [1, 2]])

not_shuffled, not_shuffled.ndim

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 1,  2]], dtype=int32)>, 2)

In [10]:
shuffled = tf.random.shuffle(not_shuffled) 

shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

In [11]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 1,  2]], dtype=int32)>

## **Other ways to create Tensors**

In [12]:
tf.ones([10,3])

<tf.Tensor: shape=(10, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [13]:
tf.zeros([10,5])

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### **Turning NumPy array into TensorFlow tensors**

**NumPy Arrays vs. TensorFlow Tensors**

> Tensors have a advantage when run over a GPU.

In [15]:
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [16]:
numpy_tensor = tf.constant(numpy_A, shape=[2, 2, 6])
numpy_tensor

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]], dtype=int32)>

## **Getting Information from Tensors**

* Shape
* Rank
* Axis/Dimension
* Size

In [17]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [18]:
# Get various attributes of tensor
print("Data-type of every element :", rank_4_tensor.dtype)
print("Number of dimensions (rank) :", rank_4_tensor.ndim)
print("Shape of tensor :", rank_4_tensor.shape)
print("Elements along axis 0 of tensor :", rank_4_tensor.shape[0])
print("Elements along last axis of tensor :", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5) :", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Data-type of every element : <dtype: 'float32'>
Number of dimensions (rank) : 4
Shape of tensor : (2, 3, 4, 5)
Elements along axis 0 of tensor : 2
Elements along last axis of tensor : 5
Total number of elements (2*3*4*5) : 120


## **Indexing our Tensors**

> Tensors can be index just like python Lists.

In [19]:
# Get The first two elements in each dimenions of our rank_4_tensor

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [20]:
# Get first elements from each dimension except the final one.
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape

TensorShape([2, 2])

In [22]:
# Adding extra dimension to our tensor 2dim->3dim
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

## **Manipulating Tensors**

### **Basic Operations**

In [23]:
tensor = tf.constant([[10, 7],
                      [3, 4]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [24]:
# We can use TF Built-in functions

tf.multiply(tensor, 10), tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  70],
        [ 30,  40]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

### **Speed test** : Python Operations v/s TF Operations

In [25]:
tensor_test = tf.constant([[0, 1],
                           [1, 0]])
import timeit

In [26]:
def speed_test(tensor_test, value):
  start = timeit.default_timer()
  for i in range(value):
    tensor_test+=1
  stop = timeit.default_timer()
  v1=stop-start
  print('Python Op Time: ', stop - start)  

  start = timeit.default_timer()
  for i in range(value):
    tensor_test = tf.add(tensor, 1)
  stop = timeit.default_timer()
  v2=stop-start
  print('TF Op Time: ', stop - start)  
  print("TF is "+str(v1/v2)+" times faster than Python")

In [27]:
# speed_test(tensor_test, 1000000)

# OUTPUT:
# Python Op Time:  29.134950077000212
# TF Op Time:  8.4106564169997
# TF is 3.4640518685452864 times faster than Python

### **Aggregating Tensors**

Condensing them from Multiple Values to a Smaller Amount of Values.

In [28]:
tensor = tf.constant([-1, -10])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -1, -10], dtype=int32)>

In [29]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 1, 10], dtype=int32)>

In [30]:
tf.reduce_min(tensor), tf.reduce_max(tensor), tf.reduce_sum(tensor)

(<tf.Tensor: shape=(), dtype=int32, numpy=-10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-11>)

In [31]:
import tensorflow_probability as tfp

tfp.stats.variance(tensor), tf.sqrt(tf.cast(tfp.stats.variance(tensor), dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int32, numpy=20>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.472136>)

### **Positional Maximum and Minimum**

In [32]:
tf.random.set_seed(42)
tensor = tf.random.uniform(shape=[50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [33]:
tf.argmax(tensor), tf.reduce_max(tensor), tensor[tf.argmax(tensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

### **Squeezing the Tensors**

In [34]:
G = tf.constant(tf.random.uniform(shape=[50]), shape = (1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [35]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

## **One Hot Encoding the Tensors** 

In [36]:
# Create a list of indices
some_list = [0, 1, 2, 3, 4]
tf.one_hot(some_list, depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [37]:
tf.one_hot(some_list, depth=5, on_value='Y', off_value='N')

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Y', b'N', b'N', b'N', b'N'],
       [b'N', b'Y', b'N', b'N', b'N'],
       [b'N', b'N', b'Y', b'N', b'N'],
       [b'N', b'N', b'N', b'Y', b'N'],
       [b'N', b'N', b'N', b'N', b'Y']], dtype=object)>